baseURL = 'https://chringel.dev'
languageCode = 'en-us'
title = 'Christian Engel'
theme = 'chringel'
pluralizelisttitles = false
paginate = 4
enableEmoji = true
enableRobotsTXT = true
author = 'Christian Engel'
copyright = 'Creative Commons Attribution 4.0 International - CC-BY'

[Params]
  description = 'My personal blog about coding, spatial stuff and everything else'
  keywords = ['blog','geo','spatial','geospatial','coding', 'web development', 'gaming', 'hugo']
  headerTitle = 'chringel@dev: ~/$'
  footerCopyrightText = 'CC BY 4.0 Christian Engel 2022'
  titleImage = 'images/index.png'
  recentPostsOnIndex = true

[Params.isso]
  enabled = true
  data = "https://comments.chringel.dev/"
  id = "thread-id"
  css = true
  lang = "en"
  replyToSelf = true
  requireAuthor = true
  requireEmail = false
  avatar = true
  avatar-bg = "#f0f0f0"
  jsLocation = "https://comments.chringel.dev/js/embed.min.js"

[Params.umami]
  enabled = true
  websiteId = "59e2e93a-9a05-4d4c-b671-33eaec1b46f7"
  jsLocation = "https://analytics.chringel.dev/umami.js"

[Params.hcard]
  avatar = "/images/index.png"
  fullName = "Christian Engel"
  pronouns = [ "he", "him" ]
  nickname = "chringel"
  showLocation = true
  city = "Potsdam"
  region = "Brandenburg"
  country = "Germany"

[Params.indieweb]
  authorizationEndpoint = "https://indieauth.com/auth"
  tokenEndpoint = "https://tokens.indieauth.com/token"

[Params.webmention]
  webmentionEndpoint = "https://jam.chringel.dev/webmention"
  webmentionPingbackEndpoint = "https://jam.chringel.dev/pingback"

[permalinks]
  posts = "/:year/:month/:slug/"
  blog = "/:year/:month/:slug/"
  page = "/:slug/"

[[menu.social]]
  name = "GitHub"
  url = "https://github.com/chringel21"

[[menu.social]]
  name = "Twitter"
  url = "https://twitter.com/DeEgge"

[[menu.social]]
  name = "Mastodon"
  url = "https://fosstodon.org/@chringel"

[[menu.social]]
  name = "RSS"
  url = "https://chringel.dev/index.xml"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[build]
  writeStats = true
