baseURL = 'https://chringel.dev/'
languageCode = 'en-us'
title = 'chringel.dev'
theme = 'chringel'
pluralizelisttitles = false
paginate = 10
enableEmoji = true
enableRobotsTXT = true
timeZone = 'Europe/Berlin'
author = 'Christian Engel'
copyright = 'Creative Commons Attribution 4.0 International - CC-BY'

[Params]
  description = 'My personal blog about coding, spatial stuff and everything else'
  headerTitle = 'chringel@dev: ~/$'
  footerCopyrightText = 'CC BY 4.0 Christian Engel {year} <br /> [Impressum](/impressum) [Privacy Protection](/privacy-protection)'
  titleImage = 'images/index.png'
  recentPostsOnIndex = true
  showPrevNextPostNavigation = false

[Params.favicons]
  appleTouchIcon = '/apple-touch-icon.png'
  icon32 = '/favicon-32x32.png'
  icon16 = '/favicon-16x16.png'
  manifest = '/site.webmanifest'
  maskIcon = '/safari-pinned-tab.svg'
  msApplicationTileColor = '#5bbad5'
  themeColor = '#ffffff'

[Params.isso]
  enabled = true
  data = "https://comments.chringel.dev/"
  id = "thread-id"
  css = true
  lang = "en"
  replyToSelf = true
  requireAuthor = true
  requireEmail = false
  avatar = true
  avatar-bg = "#f0f0f0"
  jsLocation = "https://comments.chringel.dev/js/embed.min.js"

[Params.umami]
  enabled = true
  websiteId = "59e2e93a-9a05-4d4c-b671-33eaec1b46f7"
  jsLocation = "https://analytics.chringel.dev/umami.js"

[Params.hcard]
  avatar = "/images/index.png"
  fullName = "Christian Engel"
  biography = "Hi, I'm Christian Engel, software engineer by profession, blogger, photographer and open-source enthusiast by passion."
  pronouns = [ "he", "him" ]
  nickname = "chringel"
  showLocation = true
  city = "Potsdam"
  region = "Brandenburg"
  country = "Germany"

[Params.indieweb]
  authorizationEndpoint = "https://indieauth.com/auth"
  tokenEndpoint = "https://tokens.indieauth.com/token"

[Params.webmention]
  webmentionUrl = "https://jam.chringel.dev"
  webmentionEndpoint = "/webmention"
  webmentionPingbackEndpoint = "/pingback"

[permalinks]
  posts = "/:year/:month/:slug/"
  blog = "/:year/:month/:slug/"
  notes = "/:year/:month/:day/:filename/"
  page = "/:slug/"

[taxonomies]
  categories = "categories"
  tags = "tags"
  series = "series"

[[menu.social]]
  name = "GitHub"
  url = "https://github.com/chringel21"

[[menu.social]]
  name = "Twitter"
  url = "https://twitter.com/DeEgge"

[[menu.social]]
  name = "Mastodon"
  url = "https://fosstodon.org/@chringel"

[[menu.social]]
  name = "RSS"
  url = "https://chringel.dev/index.xml"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[build]
  writeStats = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
